### ISSUE TITLE
What data is mapped to node color? Use depth?

### ISSUE THREAD

**Issue by rschwarz** [mattmilten/TreeD#1]
Cool project :-)

I could not figure out what data is used to specify the color of the nodes. Is the order in which the nodes are solved? If I could choose, I would probably use the depth.

**Comment by mattmilten** [comment]
Thanks!

The color is actually the age of the node, i.e., how many nodes have been already opened when that node was created.
You can also switch the color to represent the condition number of the corresponding LP relaxation's optimal basis matrix.

**Comment by mattmilten** [comment]
But yes, visualizing the depth might be interesting as well!

**Comment by mattmilten** [comment]
I implemented this in the meantime. You only need to set the `color` option to the specified data, e.g. `condition`, `age`, or `depth`.
