### ISSUE TITLE
Clarification of visualization: dissimilarity metric, circle vs. diamond, LP condition

### ISSUE THREAD

**Issue by ktnr** [mattmilten/TreeD#3]
Great project, thank you! I'd appreciate if you could briefly clarify the following.

1. You fill `LPSol` with values returned by `getSolVal()`. I searched the [pyscip for 'getSolVal'](https://github.com/SCIP-Interfaces/PySCIPOpt/search?q=getSolVal) but couldn't answer my question. Does it return a scalar (the value of the variable in the LP) or an object with multiple attributes? The naming suggest the value of the variable, so a scalar?

1. How is the dissimilarity metric calculated? 
In `def transform(self):` you fit your dataframe from (1-dimensional ?) objective values
```df = self.df['LPsol'].apply(pd.Series).fillna(value=0)```
with [`MDS` or `t-SNE`](https://stats.stackexchange.com/questions/223450/t-sne-versus-mds) to 2-dimensional coordinates.
How do you get from only objective values to 2D? I assume I am reading the code wrong or don't know enough about the SCIP interface, and the fit is actually performed on other attributes. Maybe the attributes in 
    ```
        self.nodelist.append({'number': node.getNumber(),
                              'LPsol': LPsol,
                              'objval': objval,
                              'parent': parent,
                              'age': age,
                              'depth':depth,
                              'first': firstlp,
                              'condition': condition,
                              'iterations': iters
                             })
    ```
    are selected?
    Then, MDS resp. t-SNE automatically selects 2 relevant dimensions from this list. Are those the same dimensions for every point? Do you have information which dimensions were chosen?

1. Just to clarify, according to the code the node types mean different things:
    ```
    # circle
    # found first LP solution of a new child node
    # parent is last LP of parent node
    ```
    ```
    # diamond
    # found an improving LP solution at the same node as before
    ```
    So the shape of the nodes contains no information on integer feasibility?

1.  The LP condition measure ([which is commented out](https://github.com/mattmilten/TreeD/blob/f0c6a98445a9f936f82ca41fe31a658936902b1a/TreeD.py#L392)) is calculated in SCIP and is a measure that is defined similarly to [the one in your other repository](https://github.com/mattmilten/condition)?

Unfortunately, I haven't (yet) managed to successfully install SCIP so that I can debug and find out myself.

**Comment by mattmilten** [comment]
Hi!

I'm happy to answer your questions.

1. Please see here for [documentation about getSolVal](https://scip-interfaces.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#adfdb30613137bed972a061c84632667b) - it does return a scalar value for the specified variable. If no solution is passed, this will return the LP solution value of that variable.

2. The dissimilarity metric is based on the location o the LP solutions of the single nodes in the n-dimensional variable space. This is reduced to a 2-dimensional space, so you can see which LP solutions are close together.

3. The shape of the node symbol signifies whether this LP solution is the first one at this node or the final one after some cuttings planes have been added.

4. The condition number is computed by the power method using the LU factorization of the optimal simplex basis matrix. This is the standard condition number for square matrices that is often used to measure the stability of solving a linear system with this matrix. This is not related to the much more complicated condition measure in my other repository.

May I ask how you found my projects or what you intend to do with them?

Cheers,
Matthias

**Comment by ktnr** [comment]
Thanks, very helpful! Re 2: Previously thought LPSol was a scalar per LP solution (= LP objective value, which made no sense at all), whereas it's a vector for a single LP solution (variable values). Debugging would have helped...

Read a comment of you on or.stackexchange, checked your zib page, got to your github. I just like to stumble upon and check out cool stuff others do. I'm looking for motivation to give SCIP a try and might play with anything SCIP-related. Other than that, I have no intention of using any of your repositories for anything other than research/recreation. Feel free to close. 

Regards,
Leopold

**Comment by mattmilten** [comment]
Cool! Feel free to stay in touch if you have any other questions or ideas.

Cheers,
Matthias
