### ISSUE TITLE
Cannot open file for reading

### ISSUE THREAD

**Issue by Zishanna** [mattmilten/TreeD#4]
Hi,
there are some problems when i want to visualize the tree of a MILP problem. The code are shown as follows:
```
from treed import TreeD

treed = TreeD(
    probpath="instance_100.lp",
    nodelimit=2000,
    showcuts=True
)

treed.solve()
fig = treed.draw()
fig.show(renderer='notebook')
```
But the MILP file cannot be open and it shows that:

```
[reader_lp.c:2438] ERROR: cannot open file <E:\代码\TreeD-main\instance_100.lp> for reading
E:\代码\TreeD-main\instance_100.lp: No error
[reader_lp.c:3550] ERROR: Error <-4> in function call
[reader_lp.c:3432] ERROR: Error <-4> in function call
Traceback (most recent call last):
  File "E:/代码/TreeD-main/trail.py", line 10, in <module>
    treed.solve()
  File "E:\代码\TreeD-main\src\treed\treed.py", line 813, in solve
    model.readProblem(self.probpath)
  File "src\pyscipopt\scip.pyx", line 4651, in pyscipopt.scip.Model.readProblem
  File "src\pyscipopt\scip.pyx", line 240, in pyscipopt.scip.PY_SCIP_CALL
OSError: SCIP: file not found error!
```

I don't know why and wish for your help. Thanks in advance!

**Comment by mattmilten** [comment]
Hi @Zishanna, this may be an issue non-ASCII characters in the file path, Please check whether the path is correct and try to use a different one that only contains ASCII characters.

**Comment by Zishanna** [comment]
Thank you for your quick reply and it is working!

**Comment by aacifuentesb** [comment]
Hi, i'm having the same issue. I follow the previous answer, making sure that there are no non-ASCII characters. What other reason could it be? Thanks in advance! 

PS. The .mps is attach
[mps_file.zip](https://github.com/mattmilten/TreeD/files/11972580/mps_file.zip)

**Comment by mattmilten** [comment]
Can you show the error message? Maybe there is something wrong with the path? You could try using an absolute path.

**Comment by aacifuentesb** [comment]
Thanks for the quick answer! I just fixed it, it was an issue with the readable file format. Thanks again!
