### ISSUE TITLE
How to get the time from the start of the program to current node?

### ISSUE THREAD

**Issue by Zishanna** [mattmilten/TreeD#5]
Hi,
I'd like to consult you some questions. There are many keys contained in dictionary `self.nodelist` in `treed.py`, which are shown as follows:

`dict_keys(['number', 'LPsol', 'objval', 'parent', 'age', 'depth', 'first', 'condition', 'iterations', 'rows', 'primalbound', 'dualbound'])`

1. What are the differences between key `number` and key `age`? 
2. If I want to know the time from the start of the program to current node, what should I do? Maybe  a new key such as `calibrated time` can be added to the dictionary `self.nodelist` .
Thank you so much.

**Comment by mattmilten** [comment]
With commit 115a717b38ec24f7b390abe698df8497b9d83316, contained in version 2.0.1, there is now also a time key to store the current solve time until this node.
Concerning the node age and number: The age is simply the total number of all nodes until this point in time, while the node number is assigned when the node is created. You can use the node age to see the order in which the nodes have been processed. 

I hope that helps. By the way: may I ask what you are using the code for?

Cheers,
Matthias

**Comment by Zishanna** [comment]
Thank you so much! This helps me a lot. I am a phd sutdent and working on AI based fast MILP problem solving. The code is used to visualize how the tree especially the priaml bound and dual bound change over time.
